import React from 'react'
import { Link } from 'react-router-dom'

const TermsConditions = () => {
  return (
    <div className='container'>
        <div className='row'>
         <h2>TERMS AND CONDITIONS</h2>
         <p>This document is an electronic record in terms of Information Technology
             Act, 2000 and rules there under as applicable and the amended provisions 
             pertaining to electronic records in various statutes as amended by the 
             Information Technology Act, 2000. This electronic record is generated by
             a computer system and does not require any physical or digital signatures.</p>
             <p>
             This document is published in accordance with the provisions of Rule 3 (1)
             of the Information Technology (Intermediaries guidelines) Rules, 2011 that
             require publishing the rules and regulations, privacy policy and Terms of
             Use for access or usage of domain name [www.BeepKart.com][www.BikeKart.com] 
             (“Website”), including the related mobile site and mobile application 
             (hereinafter referred to as “Platform”).<br/>
             <br/>
             The Platform is owned by Beep Innovations Private Limited a company incorporated
             under the Companies Act, 1956 with its registered office at B-21 2nd Floor 44 Paradise
             Apt. Laxmibai, Jagmohandas Marg, Neapean Sea Road, Mumbai, Mumbai City, Maharashtra, 
             India, 400026 (hereinafter referred to as "BeepKart").<br/>
             <br/>
             For the purpose of these Terms of Use, wherever the context so requires "You" or "User" 
             shall mean any natural or legal person who has agreed to become a buyer on the Platform 
             by providing Registration Data while registering on the Platform as Registered User 
             using the computer systems. BeepKart allows the User to surf the Platform or making 
             purchases without registering on the Platform. The term "We", "Us", "Our" shall mean 
             Beep Innovations Private Limited.<br/>
             <br/>
             When You use any of the services provided by Us through the Platform, including but 
             not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, 
             guidelines, policies, terms, and conditions applicable to such service, and they shall be 
             deemed to be incorporated into this Terms of Use and shall be considered as part and parcel 
             of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or 
             remove portions of these Terms of Use, at any time without any prior written notice to You. 
             It is Your responsibility to review these Terms of Use periodically for updates / changes. 
             Your continued use of the Platform following the posting of changes will mean that You accept 
             and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, 
             non-exclusive, non-transferable, limited privilege to enter and use the Platform.
             <br/>
             ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS 
             AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE 
             PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and 
             agree to be bound by BeepKart Policies ((including but not limited to Privacy Policy 
             available at Privacy) as amended from time to time.

             </p>
        </div>
        
    </div>
  )
}

export default TermsConditions